In [53]:
import pandas as pd
df = pd.read_csv(
'https://raw.githubusercontent.com/smirzap/AI-dengan-DL/refs/heads/main/data/BankChurners.csv')

In [54]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10127 entries, 0 to 10126
Data columns (total 23 columns):
 #   Column                                                                                                                              Non-Null Count  Dtype
---  ------                                                                                                                              --------------  -----
 0   CLIENTNUM                                                                                                                           10127 non-null  int64
 1   Attrition_Flag                                                                                                                      10127 non-null  object
 2   Customer_Age                                                                                                                        10127 non-null  int64
 3   Gender                                                                                                                              10127 non-null  object
 4   Dependent_count                                                                                                                     10127 non-null  int64
 5   Education_Level                                                                                                                     10127 non-null  object
 6   Marital_Status                                                                                                                      10127 non-null  object
 7   Income_Category                                                                                                                     10127 non-null  object
 8   Card_Category                                                                                                                       10127 non-null  object
 9   Months_on_book                                                                                                                      10127 non-null  int64
 10  Total_Relationship_Count                                                                                                            10127 non-null  int64
 11  Months_Inactive_12_mon                                                                                                              10127 non-null  int64
 12  Contacts_Count_12_mon                                                                                                               10127 non-null  int64
 13  Credit_Limit                                                                                                                        10127 non-null  float64
 14  Total_Revolving_Bal                                                                                                                 10127 non-null  int64
 15  Avg_Open_To_Buy                                                                                                                     10127 non-null  float64
 16  Total_Amt_Chng_Q4_Q1                                                                                                                10127 non-null  float64
 17  Total_Trans_Amt                                                                                                                     10127 non-null  int64
 18  Total_Trans_Ct                                                                                                                      10127 non-null  int64
 19  Total_Ct_Chng_Q4_Q1                                                                                                                 10127 non-null  float64
 20  Avg_Utilization_Ratio                                                                                                               10127 non-null  float64
 21  Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_1  10127 non-null  float64
 22  Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_2  10127 non-null  float64
dtypes: float64(7), int64(10), object(6)
memory usage: 1.8+ MB

In [55]:
df.rename(columns={'Attrition_Flag':'status'}, inplace=True)

In [56]:
df['status'].value_counts()

status
Existing Customer    8500
Attrited Customer    1627
Name: count, dtype: int64

In [57]:
#ambil pelanggan-pelanggan dengan status keluar
df_keluar = df[df['status']=='Attrited Customer']

#ambil pelanggan-pelanggan dengan status setia
df_setia = df[df['status']=='Existing Customer']

In [58]:
df_keluar_sampled = df_keluar.sample(400, random_state=2)

In [59]:
dataset = pd.concat([df_setia, df_keluar_sampled])

In [60]:
dataset['status'].value_counts()

status
Existing Customer    8500
Attrited Customer     400
Name: count, dtype: int64

In [61]:
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import recall_score

In [62]:
# Hapus kolom status sehingga yang tersisa hanya data pokok
data_pokok = dataset.drop('status', axis=1)

# Ambil kolom status dari dataset
data_label = dataset['status']

In [63]:
data_pokok.info()

<class 'pandas.core.frame.DataFrame'>
Index: 8900 entries, 0 to 7336
Data columns (total 22 columns):
 #   Column                                                                                                                              Non-Null Count  Dtype
---  ------                                                                                                                              --------------  -----
 0   CLIENTNUM                                                                                                                           8900 non-null   int64
 1   Customer_Age                                                                                                                        8900 non-null   int64
 2   Gender                                                                                                                              8900 non-null   object
 3   Dependent_count                                                                                                                     8900 non-null   int64
 4   Education_Level                                                                                                                     8900 non-null   object
 5   Marital_Status                                                                                                                      8900 non-null   object
 6   Income_Category                                                                                                                     8900 non-null   object
 7   Card_Category                                                                                                                       8900 non-null   object
 8   Months_on_book                                                                                                                      8900 non-null   int64
 9   Total_Relationship_Count                                                                                                            8900 non-null   int64
 10  Months_Inactive_12_mon                                                                                                              8900 non-null   int64
 11  Contacts_Count_12_mon                                                                                                               8900 non-null   int64
 12  Credit_Limit                                                                                                                        8900 non-null   float64
 13  Total_Revolving_Bal                                                                                                                 8900 non-null   int64
 14  Avg_Open_To_Buy                                                                                                                     8900 non-null   float64
 15  Total_Amt_Chng_Q4_Q1                                                                                                                8900 non-null   float64
 16  Total_Trans_Amt                                                                                                                     8900 non-null   int64
 17  Total_Trans_Ct                                                                                                                      8900 non-null   int64
 18  Total_Ct_Chng_Q4_Q1                                                                                                                 8900 non-null   float64
 19  Avg_Utilization_Ratio                                                                                                               8900 non-null   float64
 20  Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_1  8900 non-null   float64
 21  Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_2  8900 non-null   float64
dtypes: float64(7), int64(10), object(5)
memory usage: 1.6+ MB

In [64]:
data_pokok = pd.get_dummies(data_pokok, drop_first=True)

In [65]:
data_pokok.info()

<class 'pandas.core.frame.DataFrame'>
Index: 8900 entries, 0 to 7336
Data columns (total 35 columns):
 #   Column                                                                                                                              Non-Null Count  Dtype
---  ------                                                                                                                              --------------  -----
 0   CLIENTNUM                                                                                                                           8900 non-null   int64
 1   Customer_Age                                                                                                                        8900 non-null   int64
 2   Dependent_count                                                                                                                     8900 non-null   int64
 3   Months_on_book                                                                                                                      8900 non-null   int64
 4   Total_Relationship_Count                                                                                                            8900 non-null   int64
 5   Months_Inactive_12_mon                                                                                                              8900 non-null   int64
 6   Contacts_Count_12_mon                                                                                                               8900 non-null   int64
 7   Credit_Limit                                                                                                                        8900 non-null   float64
 8   Total_Revolving_Bal                                                                                                                 8900 non-null   int64
 9   Avg_Open_To_Buy                                                                                                                     8900 non-null   float64
 10  Total_Amt_Chng_Q4_Q1                                                                                                                8900 non-null   float64
 11  Total_Trans_Amt                                                                                                                     8900 non-null   int64
 12  Total_Trans_Ct                                                                                                                      8900 non-null   int64
 13  Total_Ct_Chng_Q4_Q1                                                                                                                 8900 non-null   float64
 14  Avg_Utilization_Ratio                                                                                                               8900 non-null   float64
 15  Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_1  8900 non-null   float64
 16  Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_2  8900 non-null   float64
 17  Gender_M                                                                                                                            8900 non-null   bool
 18  Education_Level_Doctorate                                                                                                           8900 non-null   bool
 19  Education_Level_Graduate                                                                                                            8900 non-null   bool
 20  Education_Level_High School                                                                                                         8900 non-null   bool
 21  Education_Level_Post-Graduate                                                                                                       8900 non-null   bool
 22  Education_Level_Uneducated                                                                                                          8900 non-null   bool
 23  Education_Level_Unknown                                                                                                             8900 non-null   bool
 24  Marital_Status_Married                                                                                                              8900 non-null   bool
 25  Marital_Status_Single                                                                                                               8900 non-null   bool
 26  Marital_Status_Unknown                                                                                                              8900 non-null   bool
 27  Income_Category_$40K - $60K                                                                                                         8900 non-null   bool
 28  Income_Category_$60K - $80K                                                                                                         8900 non-null   bool
 29  Income_Category_$80K - $120K                                                                                                        8900 non-null   bool
 30  Income_Category_Less than $40K                                                                                                      8900 non-null   bool
 31  Income_Category_Unknown                                                                                                             8900 non-null   bool
 32  Card_Category_Gold                                                                                                                  8900 non-null   bool
 33  Card_Category_Platinum                                                                                                              8900 non-null   bool
 34  Card_Category_Silver                                                                                                                8900 non-null   bool
dtypes: bool(18), float64(7), int64(10)
memory usage: 1.4 MB

In [66]:
data_pokok_train, data_pokok_test, data_label_train, data_label_test = train_test_split(
data_pokok, data_label,
test_size=0.3, random_state=2)

In [67]:
model = DecisionTreeClassifier(max_depth=2,random_state=2)

In [68]:
model.fit(data_pokok_train, data_label_train)

DecisionTreeClassifier(max_depth=2, random_state=2)

In [69]:
from sklearn import tree
rules = tree.export_text(model)
print(rules)

|--- feature_15 <= 0.48
|   |--- class: Existing Customer
|--- feature_15 >  0.48
|   |--- class: Attrited Customer

In [70]:
#prediksi status masing-masing pelanggan pada test set
prediksi = model.predict(data_pokok_test)
#hitung nilai Recal dari hasil prediksi
recall_score(data_label_test, prediksi, average=None)

array([1., 1.])

In [71]:
#copy dataset dari hasil pengambilan data di awal
dataset_full = df.copy(deep=True)

In [72]:
# Hapus kolom status sehingga yang tersisa hanya data pokok
data_pokok = dataset.drop('status', axis=True)
# Ambil kolom status dari dataset
data_label = dataset['status']

In [73]:
data_pokok = pd.get_dummies(
data_pokok, drop_first=True)

In [74]:
data_pokok_train, data_pokok_test, data_label_train, data_label_test = train_test_split(
data_pokok, data_label, test_size=0.3, random_state=2)

In [75]:
model2 = DecisionTreeClassifier(max_depth=2, random_state=2)

In [76]:
model2.fit(data_pokok_train, data_label_train)

DecisionTreeClassifier(max_depth=2, random_state=2)

In [77]:
rules = tree.export_text(model2)
print(rules)

|--- feature_15 <= 0.48
|   |--- class: Existing Customer
|--- feature_15 >  0.48
|   |--- class: Attrited Customer

In [78]:
prediksi = model2.predict(data_pokok_test)
recall_score(data_label_test, prediksi, average=None)

array([1., 1.])